spring:
  datasource:
    url: jdbc:postgresql://dpg-d2ve6qv5rbs73cpbe800-a:5432/yoyager
    username: root
    password: 08BC5274UD5nOMp6cDYM5qQ60YfZWs8Z
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}